name: emo_diary_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  group_button: ^5.3.4
  group_radio_button: ^1.3.0
  expandable_text: ^2.3.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.2
  http: ^0.13.3
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_database: ^10.5.1
  intl: ^0.19.0
  back_button_interceptor: ^7.0.3
  firebase_messaging: ^14.8.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
